GET http://localhost:9876/

###

GET http://localhost:9876/basket

###

POST http://localhost:9876/newURl
Content-Type: application/json

{
  "longurl": "nba.com",
  "shorturl": "basket"
}

###
post http://localhost:9876/user/signup
Content-Type: application/json

{
  "name": "Jojo",
  "password": "test",
  "email": "josh.com"
}

###
post http://localhost:9876/user/login
Content-Type: application/json

{
  "name": "Jojo",
  "password": "test"
}

### //wrong username
post http://localhost:9876/user/login
Content-Type: application/json

{
  "name": "Mojo",
  "password": "est"
}

### //wrong password
post http://localhost:9876/user/login
Content-Type: application/json

{
  "name": "Jojo",
  "password": "est"
}